### PR TITLE
Version 2.0!

### PR DESCRIPTION
**Pull request by uuf6429**
Changelog:
- not full backward compatible (hence increase in major)
- PSR-4 compliant! (each class in its own file)
- tested automatically on php 5.5, 5.6 and 7.0 (fails on hhvm for some reason)
  - ⚠️ currently bound to my travis account, this has to be fixed before merging to master
- fixed a few things in the readme
- applied license throughout the codebase
- allow connecting to server via fully-qualified address (helpful when you want to use unix domain instead of inet sockets, for example)
- badges!

### CODE REVIEW

**Comment by uuf6429** [comment]
If there is any interested to integrate my changes with the original repository, I'd be very happy to comply. Until then, I'll rely on my modified fork.

**Comment by jleeothon** [comment]
Hey @uuf6429 sorry for the criminal lateness of response. As far as I'm concerned we are not using or maintaining this package, so in the meantime we won't review this, but let me wish you good luck with your fork :)

I'll try to get some message clear on our README indicating we won't maintain it.

**Comment by uuf6429** [comment]
Hello @jleeothon!

No worries about timing.

My [heavily modified copy](https://github.com/uuf6429/dnode-php-sync-client) seems to work well since a while.

Are there any particular details I should be aware of (eg, with respect to licensing)?

**Comment by jleeothon** [comment]
Hey @uuf6429. Let me ask around in my org if that's the case :)

**Comment by jleeothon** [comment]
The full license is there, https://github.com/erasys/dnode-php-sync-client/blob/cfaf7525a091460736b45bcd7ed03b46bdc188ea/LICENSE.txt

I wouldn't give legal advice myself, but ping us if there's some peculiarity that might not suit your intended use.

**Comment by uuf6429** [comment]
OK, all's good. Thanks!

**Pull request closed without merging**
